mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.demo

spring:
  datasource:
    username: root
    password: 123456
    url: mysql://localhost:3306/ssm
    driver-class-name: com.mysql.jdbc.Driver